
# [[main]]
#   identifier = "arsenal"
#   name = "Hack Arsenal"
#   weight = 30
#   url = "/arsenal/"

[[main]]
   name = "Partners"
   url = "/partners/"
   weight = 20

[[main]]
  name = "Area Plan"
  weight = 40
  url = "/area_plan/"

[[main]]
  name = "Hack Coaches"
  weight = 50
  url = "/hack_coaches/"

[[main]]
  name = "Hardware Späti"
  weight = 60
  url = "/hardware/"

[[main]]
  name = "Hack Teams"
  weight = 100
  url = "/hack_teams/"

# [[main]]
#   identifier = "hardware"
#   name = "Hardware"
#   weight = 10
#   url = "/arsenal/hardware"
#   parent = "arsenal"

# [[main]]
#   identifier = "software"
#   name = "Software"
#   weight = 20
#   url = "/arsenal/software"
#   parent = "arsenal"


[[socials]]
  name = "Twitter"
  url = "https://twitter.com/BCWevent"

[[socials]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/company/bosch-connected-world/"

[[socials]]
name = "YouTube"
url = "https://youtu.be/8iSBWTmbGMM?si=jT0RTcff9MawCnGH"

[[socials]]
name = "Facebook"
url = "https://www.facebook.com/BoschGlobal"

[[footer]]
  name = "Corporate information"
  url = "https://bosch-connected-world.com/imprint/"

[[footer]]
  name = "Legal notice"
  url = "https://bosch-connected-world.com/legal-notice/"

[[footer]]
  name = "Data protection notice"
  url = "https://bosch-connected-world.com/data-protection-notice/"

[[footer]]
  name = "Privacy Settings"
  url = "https://bosch-connected-world.com/hackathon/bcx-event-promotion-kit/#"
