
# [[main]]
#   name = "Partners"
#   url = "/partners/"
#   weight = 20

# [[main]]
#   identifier = "arsenal"
#   name = "Hack Arsenal"
#   weight = 30
#   url = "/arsenal/"

# [[main]]
#   name = "Area Plan"
#   weight = 40
#   url = "/area_plan/"

# [[main]]
#   name = "Get Help"
#   weight = 50
#   url = "/help/"

# [[main]]
#   identifier = "hardware"
#   name = "Hardware"
#   weight = 10
#   url = "/arsenal/hardware"
#   parent = "arsenal"

# [[main]]
#   identifier = "software"
#   name = "Software"
#   weight = 20
#   url = "/arsenal/software"
#   parent = "arsenal"

[[footer]]
  name = "Corporate information"
  url = "https://bosch-connected-world.com/imprint/"

[[footer]]
  name = "Legal notice"
  url = "https://bosch-connected-world.com/legal-notice/"

[[footer]]
  name = "Data protection notice"
  url = "https://bosch-connected-world.com/data-protection-notice/"

[[footer]]
  name = "Privacy Settings"
  url = "https://bosch-connected-world.com/hackathon/bcx-event-promotion-kit/#"
